### PR TITLE
Update HDC to use id_code parameter

### LINKED ISSUE #1243: [Feature Request]: Modify calls to HDC Stats API to use new query structure
### Provide a clear and concise description of what you want to happen.

The HDC Stats API which PRISM uses for charts will be updated soon. The update includes a slight change to the parameters and URL. The following parameter changes have been been implemented on the the API that we need to accommodate in PRISM:
1.  `admin_id` is now called `id_code`
2. `vam` query argument can be omitted, in which case both `vim` & `rfh` are returned in a single response
3. `format` can be set to `csv` for csv response format (can be useful for user bulk download of tabular data). The default value is `json`

See swagger below:
- New: https://dev.api.earthobservation.vam.wfp.org/stats/docs
- Old: https://api.earthobservation.vam.wfp.org/stats/docs

Example requests:
New: 
curl -X 'GET' \
  'https://dev.api.earthobservation.vam.wfp.org/stats/admin?id_code=31&level=0&coverage=full&vam=rfh&start=2024-04-01&end=2024-04-30&format=json' \
  -H 'accept: application/json'

Old:
curl -X 'GET' \
  'https://api.earthobservation.vam.wfp.org/stats/admin/fetch?admin_id=31&level=0&coverage=full&vam=rfh&start=2024-04-01&end=2024-04-30' \
  -H 'accept: application/json'

Note that once we're ready on the PRISM side, dev.api.earthobservation.vam.wfp.org will replace  api.earthobservation.vam.wfp.org. This will be a breaking change for PRISM deployments. 

### Is there anything else you can add about the proposal? You might want to link to related issues here, if you haven't already.

@valpesendorfer - anything to add?

### PR DESCRIPTION
**Pull request by ericboucher**
### Description

This fixes #1243 

This PRs updates HDC calls to use the `id_code` parameter instead of `admin_id`.

@valpesendorfer a few questions:
- I was getting a CORS issues while testing, is there anything you can do about it?
- What endpoint do you want us to use eventually? the `dev.api` or the other one?
- For some datasets, we are still getting data through `https://api.wfp.org/hdc/1.0.0/stats/admin` using an HDC_TOKEN. Does it make sense to keep this or should we replace everything with the new endpoints? Are you planning on securing these endpoints in the future or will they stay open?

## How to test the feature:

- [ ]
- [ ]

## Checklist - did you ...

Test your changes with

- [ ] `REACT_APP_COUNTRY=rbd yarn start`
- [ ] `REACT_APP_COUNTRY=cambodia yarn start`
- [ ] `REACT_APP_COUNTRY=mozambique yarn start`
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

### CODE REVIEW

**Comment by wadhwamatic** [comment]
@ericboucher - it's working as expected except for the NDVI anomaly chart. I'm not sure if this is an issue with the request or a data error on the HDC side.

NDVI chart in this PR:
Screenshot 2024-05-16 at 10 48 55

NDVI on main branch:
Screenshot 2024-05-16 at 10 49 00


NDVI chart in chart module in this PR:
Screenshot 2024-05-16 at 10 50 36


NDVI in chart module on main branch:
Screenshot 2024-05-16 at 10 50 31

**Comment by ericboucher** [comment]
@wadhwamatic @valpesendorfer that one was previously going through the PRISM API and the other HDC backend. Looks like the data is different. @valpesendorfer can you advise on what to do here?

https://prism-api.ovio.org/hdc?level=0&admin_id=170&coverage=full&vam=vim&start=2019-05-18&end=2024-05-16
vs
https://api.earthobservation.vam.wfp.org/stats/admin?level=0&id_code=170&coverage=full&vam=vim&start=2019-05-18&end=2024-05-16

**Comment by valpesendorfer** [comment]
Looks like there was an issue on HDC side with applying a scaling factor in the anomaly calculation. It's fixed now and the two sources should give the same results now. So please proceed with the new endpoint structure.

**Review by valpesendorfer — APPROVED** [review]

**Comment by ericboucher** [comment]
Screenshot 2024-05-17 at 11 16 19 AM

Looking better, thanks @valpesendorfer

**Pull request merged**
