### PR TITLE
Fix CSV data shift when data are missing

### PR DESCRIPTION
**Pull request by HarryMytilinaios**
This fixes issue [#744].

FIxes the data shift columns in CSV when data are missing.

Also this commit fixes some unique key maps in various components that throws errors on the console.

### CODE REVIEW

**Review by ericboucher — APPROVED** [review]

**Comment by ericboucher** [comment]
@HarryMytilinaios looks good. Let's add a small test for it maybe?

**Review by wadhwamatic — APPROVED** [review]
Works as expected. Thanks @HarryMytilinaios

**Comment by HarryMytilinaios** [comment]
@ericboucher. The tests were failing before in my previous PR because I have done a generalized approch changing the csv-utils file. In this PR I have made the changes component based so only the `dowloadCSV` function inside the `ChartsPanel` component is changed. Should I write snapshot test and component test of the whole component? Or just create a small unit test that includes the `downloadCSV` function?

**Comment by ericboucher** [comment]
@HarryMytilinaios let's create a unitest for the `downloadCSV` function

**Review by ericboucher — APPROVED** [review]

**Pull request merged**
