### PR TITLE
Fix boundary dropdown issue; COUNTRY=rbd

### PR DESCRIPTION
**Pull request by ericboucher**
### Description

This fixes the print crash part of #1290 

@laurentS see my TODO which might be a better option? wdyt?

## How to test the feature:

- [ ]
- [ ]

## Checklist - did you ...

Test your changes with

- [x] `REACT_APP_COUNTRY=rbd yarn start`
- [x] `REACT_APP_COUNTRY=cambodia yarn start`
- [x] `REACT_APP_COUNTRY=mozambique yarn start`
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

### CODE REVIEW

**Comment by wadhwamatic** [comment]
@ericboucher - just verified this addresses the crash during print admin selection

**Comment by laurentS** [comment]
@ericboucher I updated your fix as per your TODO: `flattenAreaTree` now returns children of matched areas, so if you search for "Mali", you will get the country, and all its areas, on top of what was returned before (so "Mali" area in Guinea is also shown). This also changes the behaviour of the `Go To` menu (in a positive way, I think).

**Comment by ericboucher** [comment]
@laurentS thanks, working a lot better now and that's making the search functionality a lot more intuitive :)

**Comment by wadhwamatic** [comment]
Agreed, this improved the quality of results in the search and fixed the crash issue. Great work! GTG from my side

**Comment by wadhwamatic** [comment]
Two related issues?
https://github.com/WFP-VAM/prism-app/issues/1294
https://github.com/WFP-VAM/prism-app/issues/1293

**Comment by ericboucher** [comment]
@wadhwamatic the new issues you mentioned seem more likely linked to boundary file issues

**Review by wadhwamatic — APPROVED** [review]
GTG, thanks @ericboucher and @laurentS !

**Pull request merged**
