### PR TITLE
Adding capability for CSV + GeoJSON download of composite data; COUNTRY=jordan

### PR DESCRIPTION
**Pull request by gislawill**
### Description

This addresses #1336 by adding support for CSV + GeoJSON files of CDI data.

## How to test the feature:
- [ ] Open Jordan surge deployment
- [ ] Enable a CDI layer
- [ ] Select the download icon and download in both CSV and GeoJSON

## Checklist - did you ...
Test your changes with
- [ ] `REACT_APP_COUNTRY=rbd yarn start`
- [ ] `REACT_APP_COUNTRY=cambodia yarn start`
- [ ] `REACT_APP_COUNTRY=mozambique yarn start`
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

## Screenshot/video of feature:
https://www.loom.com/share/a3c8cc4955a44112a0b3ed4983bbdf7b

### CODE REVIEW

**Comment by gislawill** [comment]
"build and test api" is failing due to an unrelated outage. It should pass when we rerun in a couple hours

**Comment by gislawill** [comment]
Heads up, @wadhwamatic, geojson downloads are fixed in d1295b3

**Review by wadhwamatic — APPROVED** [review]
this looks good from my side now, thanks @gislawill 

@ericboucher - can you take a quick look?

**Review by ericboucher — APPROVED** [review]
Looks good!

Two small recommendations:
- Enhance typing around layer.type to make the code and button activation a bit cleaner
- Update `getFilename` to be more informative and contain country name + selected date for more layer types (composite in particular)

**Comment by gislawill** [comment]
Thanks for the review @ericboucher! I've updated the file name and done a small simplification of the layer types (all within LayerDownloadOptions.tsx). Could you say more on what you're thinking for the typing around layer.type? My mind jumps to using enums but not sure that'll be significantly more manageable. 

> Two small recommendations:
> 
> * Enhance typing around layer.type to make the code and button activation a bit cleaner
> * Update `getFilename` to be more informative and contain country name + selected date for more layer types (composite in particular)

**Comment by gislawill** [comment]
Hey @valpesendorfer, we've got some python tests that are hitting this service: https://api.earthobservation.vam.wfp.org/ows/?service=WCS&request=GetCoverage&....

We're seeing 500 responses which is causing our tests to fail. It appears to have been happening for a couple weeks. Any idea what's going on?

We're in the process of moving away from hitting these endpoints in our tests (using VCR.py to intercept requests and use stored response) but we'd ideally have the correct response to store in the meantime.

```
=================================== FAILURES ===================================
_____________________________ test_stats_endpoint1 _____________________________

    def test_stats_endpoint1():
        """
        Call /stats with known-good parameters.
        This endpoint can be slow (>1 min) so this test is deactivated by default.
        """
        response = client.post(
            "/stats",
            headers={"Accept": "application/json"},
            json={
                "geotiff_url": "https://api.earthobservation.vam.wfp.org/ows/?service=WCS&request=GetCoverage&version=2.0.0&coverageId=wp_pop_cicunadj&subset=Long([95](https://github.com/WFP-VAM/prism-app/actions/runs/10856592733/job/30131528361?pr=1339#step:5:96).71,[96](https://github.com/WFP-VAM/prism-app/actions/runs/10856592733/job/30131528361?pr=1339#step:5:97).68)&subset=Lat(19.42,20.33)",
                "zones_url": "https://prism-admin-boundaries.s3.us-east-2.amazonaws.com/mmr_admin_boundaries.json",
                "group_by": "TS_PCODE",
                # TODO - re-add once geonode is back online.
                # "wfs_params": {
                #     "url": "https://geonode.wfp.org/geoserver/ows",
                #     "layer_name": "mmr_gdacs_buffers",
                #     "time": "2022-10-24",
                #     "key": "label",
                # },
                "geojson_out": True,
            },
        )
>       assert response.status_code == 200
E       assert 500 == 200
E        +  where 500 = <Response [500 Internal Server Error]>.status_code

tests/test_api.py:122: AssertionError
------------------------------ Captured log call -------------------------------
ERROR    app.caching:caching.py:88 500 Server Error: Internal Server Error for url: https://api.earthobservation.vam.wfp.org/ows/?service=WCS&request=GetCoverage&version=2.0.0&coverageId=wp_pop_cicunadj&subset=Long(95.71,96.68)&subset=Lat(19.42,20.33)
```

**Comment by wadhwamatic** [comment]
gtg, thanks @gislawill!

**Comment by gislawill** [comment]
I'll merge this despite the failed test as we know it's unrelated. @ericboucher, I'm happy to make any updates to the layer typing in a follow up pr

**Pull request merged**
