### PR TITLE
Allow a user to pan, zoom and crop before 'printing' a map

### LINKED ISSUE #1019: [Feature Request]: Allow a user to pan, zoom and crop before 'printing' a map
### Provide a clear and concise description of what you want to happen.

Users want to be able to have more control when they export a map from PRISM using the 'print' feature. 

After clicking on the 'print' button, a user gets to the map preview screen. In this screen, I want to able to:
1. Pan the map
2. Zoom in/out
3. Crop the map

It's important to be able to do this in the map preview screen because the main application has other UI elements in view which obscure the map which is then exported.

Panning and zooming should behave the same as in the application (i.e. click / drag to pan, and use mouse / trackpad to zoom).

Cropping will need a new button which should be added to the right side panel:
print-update

After clicking the crop button, users should be able to drag from the edges of the canvas to crop to the area of interest similar to how photo editing software works:
https://github.com/WFP-VAM/prism-app/assets/3343536/4d4b0ceb-82cc-4e8b-bef6-5097ecbd8fb6

### Is there anything else you can add about the proposal? You might want to link to related issues here, if you haven't already.

_No response_

### PR DESCRIPTION
**Pull request by echaidemenos**
### Description

This fixes #1019 .

Adds a new button on the print dialog, enabling users to move zoom or change the output's dimentions

## How to test the feature:

- open print dialog
- use the `EDIT MAP` button 

## Checklist - did you ...

Test your changes with

- [x] `REACT_APP_COUNTRY=rbd yarn start`
- [x] `REACT_APP_COUNTRY=cambodia yarn start`
- [x] `REACT_APP_COUNTRY=mozambique yarn start`
- [x] Add / update necessary tests?
- [x] Add / update outdated documentation?

## Screenshots
Screenshot from 2024-01-26 12-17-58

Screenshot from 2024-01-26 12-17-40

### CODE REVIEW

**Comment by wadhwamatic** [comment]
Thanks @echaidemenos. This is a great start. A couple of comments / issues:
1. The footer text is getting cutoff in this PR. I just checked and it was working as expected in main
2. When I go to 'edit' the map, it's not clear that I need to click 'preview' to get back to the previous screen. Can we replace the 'preview' button with two buttons: 'ok' and 'cancel'?
3. I zoomed in and cropped to the extent I'm interested in and then clicked 'preview'. The preview screen is zoomed in and makes it difficult to see what's going on. I was expecting to see the same map view I just created when I go back. 
4. Image downloads in PNG and JPEG appear correctly. But the PDF download is zoomed in and cuts off the image.

Here's the map, cropped and zoomed as I would like to see it:
Screenshot 2024-01-23 at 14 16 46

After I click 'preview', this is what I see:
Screenshot 2024-01-23 at 14 16 59

And here are the outputs that I downloaded.

JPEG:
moz-print
PNG:
moz-print
PDF:
[moz-print.pdf](https://github.com/WFP-VAM/prism-app/files/14030362/moz-print.pdf)

**Review by ericboucher — APPROVED** [review]

**Comment by wadhwamatic** [comment]
Nice work @echaidemenos. It's good to see the preview automatically updates now. I found a few issues though:
1. If I try to print a map with a layer of type admin_level_data, the layer never renders in the print preview screen. Try Mozambique, total population as an example
2. The images used in the legend are missing for Mozambique, tropical storms
3. The bottom of the map, the scale, and the footer text are all cutoff in the PDF version I downloaded
4. Please change the stroke around the map preview to 1px, solid black

I'm also wondering, what was the rationale to only allow users to adjust the width and not the height? I was expecting both. Is there a constraint for the minimum height that we have to consider?

Issue 1, admin-level layer doesn't render
Screenshot 2024-01-29 at 11 32 14

Issue 2, missing images in legend
Screenshot 2024-01-29 at 11 39 05

Issue 3, content is cutoff in the PDF
[map (11).pdf](https://github.com/WFP-VAM/prism-app/files/14088890/map.11.pdf)

**Comment by ericboucher** [comment]
@echaidemenos I can confirm that something is broken with the PDF size. The logic doesn't seem to take into account the new aspect ratio. So if we don't change the width the image is too small and the footer is super high, and if we adjust the width then the image goes out of bounds.

**Comment by wadhwamatic** [comment]
Thanks @ericboucher. A couple of small issues though:
1. The PDF version is now slightly cutoff on the right side (see the scale on the bottom right) 
[map (15).pdf](https://github.com/WFP-VAM/prism-app/files/14090778/map.15.pdf)

2. In a couple instances, the preview kept refreshing every second or so. When that happened, and I downloaded, some elements weren't redrawn and didn't appear in the PDF 
[map (14).pdf](https://github.com/WFP-VAM/prism-app/files/14090779/map.14.pdf)

**Comment by ericboucher** [comment]
Thanks @echaidemenos changes work great and the resulting size is a lot more reasonable. I think this will help with sharing and sending via email

**Comment by wadhwamatic** [comment]
I'm periodically seeing the continuous rendering loop I mentioned earlier

https://github.com/WFP-VAM/prism-app/assets/3343536/7fd45d1c-4f71-4dc7-901a-4fefacfe7a5b

**Comment by wadhwamatic** [comment]
The map refresh loop issue is resolved now, thanks @echaidemenos. A nice to have would be to show a spinner when the print preview is re-rendering but don't worry if that will hold this PR up much further.

**Review by wadhwamatic — APPROVED** [review]
Great work @echaidemenos and thanks for the final fix @ericboucher

**Pull request merged**
