### PR TITLE
Deploy to multiple test countries

### PR DESCRIPTION
**Pull request by ericboucher**
This PR adds a small utility function to deploy surge test sites for multiple countries at once.

Simply run `yarn deploy:tests` and enter a list of space separated countries when prompted. Eg. `cambodia mozambique`

### CODE REVIEW

**Comment by wadhwamatic** [comment]
This will be a huge help when ready, thanks @ericboucher! I tried locally with three countries but got an error after the first build completed:

```
Deploying app for mozambique...
error Command "surge" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
I am confident surge does work in terminal though:
```
(base) MacBook-Pro-14:frontend amit$ surge
   Running as awadhwa@gmail.com (Student)
        project: /Users/amit/dev/PRISM-Main/prism-app/frontend/
```

**Comment by ericboucher** [comment]
@wadhwamatic sorry for not mentioning it in the PR, you need to run "yarn install" first

**Comment by wadhwamatic** [comment]
@ericboucher - I was prompted to enter the domain in the terminal for each deployment. Looks like that parameter isn't getting added to surge automatically.

Screenshot 2023-11-27 at 16 36 05

**Comment by ericboucher** [comment]
@wadhwamatic looks like you added `,` between countries which got picked up. At the moment the script is configured for space-separated inputs. We can change to comma separated if you prefrer. I'll add an option to remove commas jic

**Comment by wadhwamatic** [comment]
Thanks, and sorry not sure why I added commas! Thanks for handling that. This is working as expected. Great stuff, thanks Eric.

**Review by wadhwamatic — APPROVED** [review]

**Pull request merged**
