### PR TITLE
Add new layers; COUNTRY=rbd

### PR DESCRIPTION
**Pull request by wadhwamatic**
### Description

Add new layers to RBD and allow point_data layers to be displayed as hexagons.
Add a new round of CH data

TODO
- [x] review point_data layer changes and make them reusable

## How to test the feature:

- [ ] Load new layers (Future of the Lean Season, Cropland Change Analysis, Conflict Analysis)
- [ ] Verify new round of CH data (Feb - May 2024)

## Checklist - did you ...

Test your changes with

- [ ] `REACT_APP_COUNTRY=rbd yarn start`
- [ ] `REACT_APP_COUNTRY=cambodia yarn start`
- [ ] `REACT_APP_COUNTRY=mozambique yarn start`
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

### CODE REVIEW

**Comment by wadhwamatic** [comment]
@ericboucher - I experimented with the H3 resolution. The ideal state would be to have a more dynamic resolution based on the zoom level. A resolution of 7 is better for data visualization but doesn't appear at the default zoom level. I think the hierarchy functions in H3 could help address this. What do you think? https://h3geo.org/docs/api/hierarchy

**Comment by ericboucher** [comment]
@wadhwamatic possible but a bit tricky. Usually point data like this needs to be in grid structure reasy to be used as hex which does not seem to be the case here?

**Comment by wadhwamatic** [comment]
@ericboucher 

> Usually point data like this needs to be in grid structure ready to be used as hex with a specific resolution based on the distance between points, which does not seem to be the case here?

That's correct, this is point data, not gridded.

> I can simply adjust the resolution with the zoom level for now maybe?

Not sure what you mean - by changing the zoom for RBD overall, or by adjusting the zoom if this layer is selected? If the latter, that works well!

**Comment by wadhwamatic** [comment]
@ericboucher - I added a second point layer for the crop analysis. There's one for 2023 vs 2022, and another for 2023 vs reference years. If I select a second layer from the group, both appear. Instead, we should only show one layer at a time. Hope that's an easy fix.

**Comment by wadhwamatic** [comment]
@ericboucher - this looks good from my side. I tested all new layers in RBD including the cropland change, and also verified that point layers in cambodia still work as expected. please go ahead and merge when you're ready

**Comment by ericboucher** [comment]
Not "related" but one thing I noticed reviewing the PR is that the data files for RBD are getting quite big. I would recommend:
- removing all unnecessary fields
- removing key/values where the value is `null`
- minify JSON files

**Review by ericboucher — APPROVED** [review]

**Pull request merged**
