### PR TITLE
Update geoserver url to use public sparc instance COUNTRY=mozambique

### PR DESCRIPTION
**Pull request by JorgeMartinezG**
This fixes issue [enter issue number].

How to test the feature:
- Using mozambique country load tropical storms layer.

### CODE REVIEW

**Review by ericboucher — APPROVED** [review]
Is this a temporary fix or is the sparc instance gonna stay up a while?

**Comment by wadhwamatic** [comment]
a few config changes I had made to the other mozambique branch were overwritten. add them back but i'm running into a couple of issues. i'll try and sort this out later today

**Comment by wadhwamatic** [comment]
> Is this a temporary fix or is the sparc instance gonna stay up a while?

@ericboucher - it's temporary, but i don't have much insight into how long

**Comment by wadhwamatic** [comment]
@ericboucher - I needed to add back the short term fix we added for another chart param. You had looked at it before in another PR: https://github.com/WFP-VAM/prism-app/pull/767/commits/ac6c4286742d4afa28e7d060bead1ce0d0d70060

It might need to change again when we work on this issue https://github.com/WFP-VAM/prism-app/issues/791 cc: @reed1

**Review by ericboucher — APPROVED** [review]

**Pull request merged**
