### PR TITLE
Add logo to print mode

### LINKED ISSUE #1223: [Feature Request]: Add option to display custom logo when printing
### Provide a clear and concise description of what you want to happen.

Users have asked to be able to show their logo in the map print view. Can we reuse the logo in prism.json and add include it in the map easily, like below? The logo position could be top left or right, or hidden.

Screenshot 2024-04-30 at 17 33 50

### Is there anything else you can add about the proposal? You might want to link to related issues here, if you haven't already.

_No response_

### PR DESCRIPTION
**Pull request by ericboucher**
### Description

This fixes #1223.

## How to test the feature:

- [ ]
- [ ]

## Checklist - did you ...

Test your changes with

- [ ] `REACT_APP_COUNTRY=rbd yarn start`
- [ ] `REACT_APP_COUNTRY=cambodia yarn start`
- [ ] `REACT_APP_COUNTRY=mozambique yarn start`
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

## Screenshot/video of feature:
Screenshot 2024-05-03 at 11 22 51 AM
Screenshot 2024-05-03 at 11 22 57 AM

### CODE REVIEW

**Comment by wadhwamatic** [comment]
This looks good, thanks. I would anticipate the next thing the Mozambique govt partner will ask for is to scale the size of the logo. Can we add this option too?

**Comment by ericboucher** [comment]
How many options?

**Comment by wadhwamatic** [comment]
> How many options?

How about either as a percent: 50%, 75%, 100%, 125%, 150%
Or small (0.5x), medium (1x), large (1.5x)?

100% / medium would equal the size shown in the header in the app

**Comment by ericboucher** [comment]
@wadhwamatic I pushed a change with S/M/L, let me know what you think:
Screenshot 2024-05-03 at 10 58 20 PM

**Comment by wadhwamatic** [comment]
> @wadhwamatic I pushed a change with S/M/L, let me know what you think

Looks good to me, thanks! Can we make the labels translatable? I think S/M/L is pretty universally known, but good to have an option to change.

I found that the logo only shows if you click the position button. Clicking the visibility the icon doesn't show it

**Comment by ericboucher** [comment]
You mean clicking the size directly? The size selector is disabled/greyed-out if the the logo is not on. But I can change that logic if you'd like

**Comment by wadhwamatic** [comment]
> You mean clicking the size directly? The size selector is disabled/greyed-out if the the logo is not on. But I can change that logic if you'd like

No, I mean that when the print screen first opens, the logo is not visible. If you then click on the visibility icon, nothing happens. The logo only shows if you click on the logo position button.

**Comment by ericboucher** [comment]
@wadhwamatic I improved the behavior a bit, I think we should merge this as is and improve the toggles later based on @Marco6x1 designs [linked here](https://www.figma.com/file/5GX8jVxBCfLrcfkTniRvFi/WFP-Prism?type=design&node-id=665-2648&mode=design&t=99hzmpXa0KOlnRMJ-0)

**Review by wadhwamatic — APPROVED** [review]

**Comment by wadhwamatic** [comment]
> @wadhwamatic I improved the behavior a bit, I think we should merge this as is and improve the toggles later based on @Marco6x1 designs [linked here](https://www.figma.com/file/5GX8jVxBCfLrcfkTniRvFi/WFP-Prism?type=design&node-id=665-2648&mode=design&t=99hzmpXa0KOlnRMJ-0)

@ericboucher - this looks good thanks. I like the designs @Marco6x1 has proposed, which feel more uniform with the layer navigation UI. Shall we put that in a new issue (good first issue for collaborators?).

**Pull request merged**
