### PR TITLE
Revamp print UI and add admin area mask

### LINKED ISSUE #1076: [Feature Request]: Revisit print UI, including additional elements - title and text size
### Provide a clear and concise description of what you want to happen.

Users have requested that we provide the option to include a title when we print a map, and to make the footer text size adjustable.

Let's revisit the print feature UI while we are at it.  I think we should allow all text elements to have adjustable sizes. They could just be small, medium, large to not make things too complicated. It would also be good if we can edit text in the same screen instead of loading a modal.

Below is just a suggestion and includes a change mentioned in issue 1051. @ericboucher, can we have Marc also take a look?
crop-map

### Is there anything else you can add about the proposal? You might want to link to related issues here, if you haven't already.

See issue https://github.com/WFP-VAM/prism-app/issues/1051

_No response_

### PR DESCRIPTION
**Pull request by echaidemenos**
### Description

This fixes #1076 .

Changes the styles of print UI

- [x] Footer Text smooth updates. (could be solved by drawing footer as a div and not a canvas)
- [x] Add title text
- [x] Add search for admin area
- [x] Align TextField and buttons (should work for all screen sizes)
- [x] Fix scroll
- [x] mask should cover selected admin area only
- [x] move "Map Options" above and update font (see Figma)
- [x] reduce spacing between the panning instructions and the map
- [x] Add a filename
- [x] show the selected admin area (fixing in #1127)

## How to test the feature:

- [ ] Play around with the print module, including the mask and admin area selection

## Checklist - did you ...

Test your changes with

- [ ] `REACT_APP_COUNTRY=rbd yarn start`
- [ ] `REACT_APP_COUNTRY=cambodia yarn start`
- [ ] `REACT_APP_COUNTRY=mozambique yarn start`
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

## Screenshot/video of feature:

Screenshot 2024-02-19 at 7 40 35 PM

### CODE REVIEW

**Comment by Marco6x1** [comment]
Hello!
- Map width fine for me, can we not display the eye as it's not relevant? To keep things ordered, we can add a 50%
- I have a slight preference for displaying font sizes instead of % for Legend but it's not the end of the world
- Legend font looks weird (like reduced in height)
That's all for me. Looks good!

**Comment by ericboucher** [comment]
@wadhwamatic I deactivated the zoom when we select an admin boundary for the mask but let us know if you prefer to have it on.

**Comment by wadhwamatic** [comment]
This is looking great, nice work. I found a couple of issues:
1. When resizing the the map width and then saving as a PDF. The example below results from setting the the map width to 50%. 
2. I found that the preview redraws a bit too fast. I.e., I'm still zooming / panning and it begins to redraw. Can we delay this by another 2-3 seconds?

[map (14).pdf](https://github.com/WFP-VAM/prism-app/files/14382180/map.14.pdf)

**Comment by wadhwamatic** [comment]
> @wadhwamatic I deactivated the zoom when we select an admin boundary for the mask but let us know if you prefer to have it on.

@ericboucher - yup, that is fine. I think we can remove the multi-select option. Is this simple to do without affecting the primary go to feature?

**Comment by ericboucher** [comment]
@wadhwamatic we fixed the issues you mentioned, I also added a better filename `country_date`

**Review by ericboucher — APPROVED** [review]

**Comment by wadhwamatic** [comment]
> @wadhwamatic we fixed the issues you mentioned, I also added a better filename `country_date`

@ericboucher - since we're changing this - can we use the map title field + date instead? That way if a user changes the map title for their needs, it's also reflected in the filename.

**Comment by wadhwamatic** [comment]
@echaidemenos - great work on this. Looks good to me now. There's just the small question around the filename, then we can merge.

**Review by wadhwamatic — APPROVED** [review]

**Pull request merged**
