### PR TITLE
Download admin level data COUNTRY=rbd

### PR DESCRIPTION
**Pull request by ajanim**
- [ ] Related issue: [Download admin level layer as either CSV or GeoJSON](https://github.com/WFP-VAM/prism-app/issues/209)
- [ ] How to test the feature:
  - [ ] Load admin data
  - [ ] Witness multi-option download button in the legend that downloads data as .csv or .geojson
- [ ] Screenshot/video of feature:

image

### CODE REVIEW

**Comment by wadhwamatic** [comment]
@sifelix - I tried to pull this PR locally but ran into errors. I also tried a clean yarn install but hitting the same issue. Here's the error:

husky > pre-commit (node v16.14.0)
Preparing... [started]
Preparing... [completed]
Running tasks... [started]
Running tasks for src/**/*.{js,jsx,ts,tsx} [started]
yarn run lint --fix [started]
yarn run lint --fix [failed]
→ 
Running tasks for src/**/*.{js,jsx,ts,tsx} [failed]
→ 
Running tasks... [failed]
Applying modifications... [started]
Applying modifications... [skipped]
→ Skipped because of errors from tasks.
Reverting to original state... [started]
Reverting to original state... [completed]
Cleaning up... [started]
Cleaning up... [completed]



✖ yarn found some errors. Please fix them and try committing again.
$ eslint --ext .js,.jsx,.ts,.tsx -c .eslintrc ./src ../common/src --fix /Users/amit/dev/PRISM-Main/prism-app/frontend/src/components/MapView/Legends/AdminLevelDataDownloadButton.tsx /Users/amit/dev/PRISM-Main/prism-app/frontend/src/components/MapView/Legends/AnalysisDownloadButton.tsx /Users/amit/dev/PRISM-Main/prism-app/frontend/src/utils/csv-utils.test.ts /Users/amit/dev/PRISM-Main/prism-app/frontend/src/utils/csv-utils.ts

/Users/amit/dev/PRISM-Main/prism-app/frontend/src/components/MapView/Legends/AdminLevelDataDownloadButton.tsx
56:5  warning  Unexpected console statement  no-console

/Users/amit/dev/PRISM-Main/prism-app/frontend/src/utils/csv-utils.test.ts
1:8  warning  'React' is defined but never used  no-unused-vars
1:8  warning  'React' is defined but never used  @typescript-eslint/no-unused-vars

/Users/amit/dev/PRISM-Main/prism-app/common/src/base/test.ts
2:18  error  Unable to resolve path to module 'flug'  import/no-unresolved

/Users/amit/dev/PRISM-Main/prism-app/common/src/gml/test.ts
1:18  error  Unable to resolve path to module 'flug'  import/no-unresolved

/Users/amit/dev/PRISM-Main/prism-app/common/src/ows/test.ts
1:18  error  Unable to resolve path to module 'flug'  import/no-unresolved

/Users/amit/dev/PRISM-Main/prism-app/common/src/utils/bbox.ts
1:15  warning  'BBOX' is defined but never used  no-unused-vars

/Users/amit/dev/PRISM-Main/prism-app/common/src/utils/image.ts
2:15  warning  'BBOX' is defined but never used  no-unused-vars

/Users/amit/dev/PRISM-Main/prism-app/common/src/utils/test.ts
1:15  error  Unable to resolve path to module 'flug'  import/no-unresolved

/Users/amit/dev/PRISM-Main/prism-app/common/src/wcs/WCS/test.ts
2:18  error  Unable to resolve path to module 'flug'  import/no-unresolved
3:23  error  Unable to resolve path to module 'srvd'  import/no-unresolved

/Users/amit/dev/PRISM-Main/prism-app/common/src/wcs/WCSLayer/index.ts
1:15  warning  'MakeOptional' is defined but never used  no-unused-vars

/Users/amit/dev/PRISM-Main/prism-app/common/src/wcs/utils/index.ts
20:15  warning  'BBOX' is defined but never used  no-unused-vars

/Users/amit/dev/PRISM-Main/prism-app/common/src/wcs/utils/test.ts
2:25  error  Unable to resolve path to module 'find-and-read'  import/no-unresolved
3:18  error  Unable to resolve path to module 'flug'           import/no-unresolved

/Users/amit/dev/PRISM-Main/prism-app/common/src/wfs/test.ts
1:25  error  Unable to resolve path to module 'find-and-read'  import/no-unresolved
2:18  error  Unable to resolve path to module 'flug'           import/no-unresolved

/Users/amit/dev/PRISM-Main/prism-app/common/src/wfs/utils.ts
21:15  warning  'BBOX' is defined but never used  no-unused-vars

/Users/amit/dev/PRISM-Main/prism-app/common/src/wms/WMS/test.ts
1:18  error  Unable to resolve path to module 'flug'  import/no-unresolved
3:23  error  Unable to resolve path to module 'srvd'  import/no-unresolved

/Users/amit/dev/PRISM-Main/prism-app/common/src/wms/utils/index.ts
 11:15  warning  'WMS_OUTPUT_FORMAT' is defined but never used  no-unused-vars
144:7   warning  Unallowed reassignment                         fp/no-mutation

/Users/amit/dev/PRISM-Main/prism-app/common/src/wms/utils/test.ts
1:25  error  Unable to resolve path to module 'find-and-read'  import/no-unresolved
2:18  error  Unable to resolve path to module 'flug'           import/no-unresolved

✖ 24 problems (14 errors, 10 warnings)

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
husky > pre-commit hook failed (add --no-verify to bypass)

**Comment by DanielJDufour** [comment]
@wadhwamatic , have you run `yarn run setup:common`?  The modules that can't be found (flug, srvd, and find-and-read) should be installed by that command.

**Comment by wadhwamatic** [comment]
> @wadhwamatic , have you run `yarn run setup:common`? The modules that can't be found (flug, srvd, and find-and-read) should be installed by that command.

Thanks Daniel. After doing a clean pull from this branch and fresh yarn install followed by setup:common I was able to test locally.

@sifelix - I ran into two issues:
1. If you activate a WMS layer and an admin level data layer, and then try to download the admin level data layer, we’re incorrectly adding the date to the filename. 
2. The CSV file seems to be using a semi-colon instead of a comma as a delimiter

**Comment by sifelix** [comment]
> > @wadhwamatic , have you run `yarn run setup:common`? The modules that can't be found (flug, srvd, and find-and-read) should be installed by that command.
> 
> Thanks Daniel. After doing a clean pull from this branch and fresh yarn install followed by setup:common I was able to test locally.
> 
> @sifelix - I ran into two issues:
> 
> 1. If you activate a WMS layer and an admin level data layer, and then try to download the admin level data layer, we’re incorrectly adding the date to the filename.
> 2. The CSV file seems to be using a semi-colon instead of a comma as a delimiter

1 - is updated
2 - I added the tag sep=; at the beginning of the csv as you asked

**Comment by wadhwamatic** [comment]
> 1 - is updated
> 2 - I added the tag sep=; at the beginning of the csv as you asked

@sifelix - all looks good now. I verified dates do not appear in the filename unless the dataset has a time dimensions. CSVs work as expected too. Thanks

**Review by wadhwamatic — APPROVED** [review]
GTG per @ericboucher and me. Thanks!

**Pull request merged**
